"""init_15_tables

Revision ID: c4b1c5249d34
Revises: 
Create Date: 2026-03-17 13:15:25.908423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b1c5249d34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_snippet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_no', sa.String(length=20), nullable=False, comment='章节编号'),
    sa.Column('chapter_name', sa.String(length=100), nullable=False, comment='章节名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容片段(Jinja2 模板)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_snippet_tenant_id'), 'chapter_snippet', ['tenant_id'], unique=False)
    op.create_table('doc_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='模板文件 OSS 地址'),
    sa.Column('is_default', sa.Integer(), nullable=False, comment='是否默认模板'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_template_tenant_id'), 'doc_template', ['tenant_id'], unique=False)
    op.create_table('eng_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='案例名称'),
    sa.Column('mine_name', sa.String(length=100), nullable=True, comment='矿井名称'),
    sa.Column('excavation_type', sa.String(length=20), nullable=True, comment='掘进类型'),
    sa.Column('rock_class', sa.String(length=10), nullable=True, comment='围岩级别'),
    sa.Column('summary', sa.Text(), nullable=True, comment='案例摘要'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='案例文件 OSS 地址'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_case_tenant_id'), 'eng_case', ['tenant_id'], unique=False)
    op.create_table('rule_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则组名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则组描述'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_group_tenant_id'), 'rule_group', ['tenant_id'], unique=False)
    op.create_table('std_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='规范名称'),
    sa.Column('doc_type', sa.String(length=30), nullable=False, comment='文档类型(法律法规/技术规范/集团标准/安全规程)'),
    sa.Column('version', sa.String(length=30), nullable=True, comment='版本号'),
    sa.Column('publish_date', sa.Date(), nullable=True, comment='发布日期'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否现行有效'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='原文件 OSS 地址'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_std_document_tenant_id'), 'std_document', ['tenant_id'], unique=False)
    op.create_table('sys_mine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='矿井名称'),
    sa.Column('company', sa.String(length=200), nullable=True, comment='所属公司'),
    sa.Column('gas_level', sa.String(length=20), nullable=True, comment='瓦斯等级(低/高/突出)'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='矿井地址'),
    sa.Column('contact', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False, comment='矿井ID'),
    sa.Column('face_name', sa.String(length=100), nullable=False, comment='工作面名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='项目状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['mine_id'], ['sys_mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tenant_id'), 'project', ['tenant_id'], unique=False)
    op.create_table('rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='规则类型(支护/装备/安全/断面/通风)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级(数值越大优先级越高)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['rule_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_tenant_id'), 'rule', ['tenant_id'], unique=False)
    op.create_table('std_clause',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父条款ID（树形结构）'),
    sa.Column('clause_no', sa.String(length=30), nullable=True, comment='条款编号'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='条款标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='条款正文'),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级深度'),
    sa.ForeignKeyConstraint(['document_id'], ['std_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='bcrypt哈希密码'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_sys_user_tenant_id'), 'sys_user', ['tenant_id'], unique=False)
    op.create_table('generated_doc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文档 OSS 地址'),
    sa.Column('file_name', sa.String(length=200), nullable=False, comment='文件名'),
    sa.Column('file_size_mb', sa.Float(), nullable=True, comment='文件大小(MB)'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_doc_tenant_id'), 'generated_doc', ['tenant_id'], unique=False)
    op.create_table('project_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rock_class', sa.String(length=10), nullable=True, comment='围岩级别(I/II/III/IV/V)'),
    sa.Column('coal_thickness', sa.Float(), nullable=True, comment='煤层厚度(m)'),
    sa.Column('coal_dip_angle', sa.Float(), nullable=True, comment='煤层倾角(°)'),
    sa.Column('gas_level', sa.String(length=20), nullable=True, comment='瓦斯等级(低/高/突出)'),
    sa.Column('hydro_type', sa.String(length=50), nullable=True, comment='水文地质类型'),
    sa.Column('geo_structure', sa.String(length=200), nullable=True, comment='地质构造特征'),
    sa.Column('spontaneous_combustion', sa.String(length=20), nullable=True, comment='自燃倾向性'),
    sa.Column('roadway_type', sa.String(length=30), nullable=True, comment='巷道类型(进风巷/回风巷/...)'),
    sa.Column('excavation_type', sa.String(length=20), nullable=True, comment='掘进类型(煤巷/岩巷/半煤岩巷)'),
    sa.Column('section_form', sa.String(length=20), nullable=True, comment='断面形式(矩形/拱形/梯形)'),
    sa.Column('section_width', sa.Float(), nullable=True, comment='断面宽(m)'),
    sa.Column('section_height', sa.Float(), nullable=True, comment='断面高(m)'),
    sa.Column('excavation_length', sa.Float(), nullable=True, comment='掘进长度(m)'),
    sa.Column('service_years', sa.Integer(), nullable=True, comment='服务年限'),
    sa.Column('dig_method', sa.String(length=20), nullable=True, comment='掘进方式(综掘/炮掘/手工)'),
    sa.Column('dig_equipment', sa.String(length=100), nullable=True, comment='掘进设备型号'),
    sa.Column('transport_method', sa.String(length=100), nullable=True, comment='运输方式'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID（矿井ID）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_project_params_tenant_id'), 'project_params', ['tenant_id'], unique=False)
    op.create_table('rule_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('target_chapter', sa.String(length=50), nullable=False, comment='目标章节编号'),
    sa.Column('snippet_id', sa.Integer(), nullable=True, comment='关联的章节内容片段 ID'),
    sa.Column('params_override', sa.JSON(), nullable=True, comment='参数覆盖(JSON)'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False, comment='条件字段(rock_class/gas_level/coal_thickness 等 ProjectParams 字段)'),
    sa.Column('operator', sa.String(length=10), nullable=False, comment='运算符(eq/ne/gt/lt/gte/lte/in/between/contains)'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='条件值(JSON 序列化)'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_condition')
    op.drop_table('rule_action')
    op.drop_index(op.f('ix_project_params_tenant_id'), table_name='project_params')
    op.drop_table('project_params')
    op.drop_index(op.f('ix_generated_doc_tenant_id'), table_name='generated_doc')
    op.drop_table('generated_doc')
    op.drop_index(op.f('ix_sys_user_tenant_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('std_clause')
    op.drop_index(op.f('ix_rule_tenant_id'), table_name='rule')
    op.drop_table('rule')
    op.drop_index(op.f('ix_project_tenant_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('sys_role')
    op.drop_table('sys_mine')
    op.drop_index(op.f('ix_std_document_tenant_id'), table_name='std_document')
    op.drop_table('std_document')
    op.drop_index(op.f('ix_rule_group_tenant_id'), table_name='rule_group')
    op.drop_table('rule_group')
    op.drop_index(op.f('ix_eng_case_tenant_id'), table_name='eng_case')
    op.drop_table('eng_case')
    op.drop_index(op.f('ix_doc_template_tenant_id'), table_name='doc_template')
    op.drop_table('doc_template')
    op.drop_index(op.f('ix_chapter_snippet_tenant_id'), table_name='chapter_snippet')
    op.drop_table('chapter_snippet')
    # ### end Alembic commands ###
