"""initial_schema

Revision ID: 0689c114187d
Revises: 
Create Date: 2026-03-19 12:35:33.060520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0689c114187d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_log', 'diff_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='编辑差异度 0~1（仅 edit 动作有值）',
               existing_nullable=True)
    op.drop_index(op.f('ix_std_clause_embedding'), table_name='std_clause', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_sys_mine_tenant_id'), 'sys_mine', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_role_tenant_id'), 'sys_role', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_role_tenant_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_mine_tenant_id'), table_name='sys_mine')
    op.create_index(op.f('ix_std_clause_embedding'), 'std_clause', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('feedback_log', 'diff_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='编辑差异度 0~1（仅 edit 动作有值）',
               existing_nullable=True)
    # ### end Alembic commands ###
